/**
 * filename: backend/routes/certificateRoutes.js
 * purpose: Generate printable blockchain authenticity certificates as PDF.
 * setup notes: Requires pdfkit and qrcode dependencies.
 */
const express = require("express");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");
const { getContract, CONTRACT_ADDRESS } = require("../contract");

const router = express.Router();

function formatDate(isoDate) {
  return new Date(isoDate).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });
}

function drawTableHeader(doc, y) {
  doc.font("Helvetica-Bold").fontSize(9);
  doc.text("Step #", 40, y);
  doc.text("Status", 90, y);
  doc.text("Location", 170, y);
  doc.text("Timestamp", 310, y);
  doc.text("Updated By", 430, y);
  doc.moveTo(40, y + 14).lineTo(570, y + 14).strokeColor("#cccccc").stroke();
}

router.get("/certificate/:productId", async (req, res) => {
  try {
    const { productId } = req.params;
    const contract = await getContract();
    const product = await contract.getProduct(productId);
    const historyRaw = await contract.getProductHistory(productId);
    const history = historyRaw.map((step) => ({
      status: step.status,
      location: step.location,
      timestamp: new Date(Number(step.timestamp) * 1000).toISOString(),
      updatedBy: step.updatedBy
    }));

    const qrDataUrl = await QRCode.toDataURL(`http://localhost:5173/product/${productId}`);
    const qrBase64 = qrDataUrl.replace(/^data:image\/png;base64,/, "");
    const qrBuffer = Buffer.from(qrBase64, "base64");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="certificate-${productId}.pdf"`);

    const doc = new PDFDocument({ size: "A4", margin: 40 });
    doc.pipe(res);

    doc.font("Helvetica-Bold").fontSize(20).text("Blockchain Authenticity Certificate", 40, 40);
    doc.font("Helvetica").fontSize(12).fillColor("#555555").text("Verified Supply Chain Record", 40, 68);
    doc
      .fontSize(10)
      .fillColor("#333333")
      .text(`Date issued: ${new Date().toLocaleDateString("en-GB")}`, 40, 88);

    doc.font("Helvetica-Bold").fontSize(13).text("Product Info", 40, 120);
    doc.font("Helvetica").fontSize(10).text(`Product Name: ${product.name}`, 40, 142);
    doc.text(`Product ID: ${Number(product.id)}`, 40, 158);
    doc.text(`Current Owner: ${product.currentOwner}`, 40, 174);
    doc.text(`Total Steps in Chain: ${history.length}`, 40, 190);

    doc.font("Helvetica-Bold").fontSize(13).text("Supply Chain History", 40, 222);
    let tableY = 244;
    drawTableHeader(doc, tableY);
    tableY += 20;

    doc.font("Helvetica").fontSize(8);
    history.forEach((step, index) => {
      if (tableY > 730) {
        doc.addPage();
        tableY = 50;
        drawTableHeader(doc, tableY);
        tableY += 20;
        doc.font("Helvetica").fontSize(8);
      }

      doc.text(String(index + 1), 40, tableY);
      doc.text(step.status, 90, tableY, { width: 75 });
      doc.text(step.location, 170, tableY, { width: 130 });
      doc.text(formatDate(step.timestamp), 310, tableY, { width: 110 });
      doc.text(step.updatedBy, 430, tableY, { width: 140 });
      doc.moveTo(40, tableY + 14).lineTo(570, tableY + 14).strokeColor("#efefef").stroke();
      tableY += 18;
    });

    const proofY = Math.min(tableY + 20, 670);
    doc.font("Helvetica-Bold").fontSize(12).fillColor("#222222").text("Blockchain Proof", 40, proofY);
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#333333")
      .text(
        "This product's journey is immutably recorded on the Ethereum blockchain. Each entry is cryptographically secured and tamper-proof.",
        40,
        proofY + 20,
        { width: 350 }
      );
    doc.text(`Contract Address: ${CONTRACT_ADDRESS}`, 40, proofY + 58, { width: 350 });

    doc.image(qrBuffer, 445, proofY + 10, { fit: [120, 120] });
    doc.font("Helvetica").fontSize(8).text("Scan to verify live record", 455, proofY + 132);

    doc
      .font("Helvetica-Oblique")
      .fontSize(9)
      .fillColor("#666666")
      .text("Generated by SupplyChain DApp | Powered by Ethereum", 40, 800, {
        align: "center",
        width: 520
      });

    doc.end();
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to generate certificate"
    });
  }
});

module.exports = router;
